name: app_theme_mode
description: Widgets to control your app theme mode during runtime and save it how you wishing.
version: 1.0.0
homepage: https://github.com/kmartins/app_theme_mode

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
